Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2023-05, with the labels that each got.

#52 [Task] Display actual currency
  src/OrderManager/Order/Listing.php
  src/OrderManager/V7/OrderAgent.php
  src/Resources/views/admin_order/list.html.twig
Labels: Task

#54 [Bug] Fixing Voucher Generation
  src/Controller/VoucherController.php
  src/Resources/public/vendor/bootstrap4/css/bootstrap.css
  src/Resources/public/vendor/bootstrap4/css/bootstrap.min.css
  src/Resources/public/vendor/bootstrap4/js/bootstrap-native-v4.min.js
  src/Resources/public/vendor/chart.doughnut.js
  src/Resources/public/vendor/chart.min.js
  src/Resources/public/vendor/flatpickr.min.css
  src/Resources/public/vendor/flatpickr.min.js
  src/Resources/views/admin_order/detail.html.twig
  src/Resources/views/back-office.html.twig
  src/Resources/views/voucher/parts/modals/cleanup_reservations_modal.html.twig
  src/Resources/views/voucher/parts/modals/pattern/cleanup_modal.html.twig
  src/Resources/views/voucher/parts/modals/pattern/generate_modal.html.twig
  src/Resources/views/voucher/parts/modals/single/assign_settings_modal.html.twig
  src/Resources/views/voucher/voucher_code_tab_pattern.html.twig
  src/Resources/views/voucher/voucher_code_tab_single.html.twig
  src/Resources/views/voucher/voucher_layout.html.twig
  src/VoucherService/TokenManager/Pattern.php
Labels: Bug

#58 [Bug] Fix empty online shop order
  src/Model/Currency.php
  src/Resources/views/admin_order/detail.html.twig
Labels: Bug

#60 Fix: Monolog handler name
  src/Resources/config/pimcore/config.yaml
Labels: Bug

#56 [Bug] Fix Installer
  src/IndexService/Config/AbstractConfig.php
  src/Tools/Installer.php
Labels: Bug

#61 [Task] Removed html sanitizer
  src/PricingManager/Rule.php
  src/Resources/public/js/pricing/config/item.js
Labels: Task

#59 [Github Action] Setup PO editor
  .github/workflows/poeditor-export.yaml
Labels: Task

#65 Fix default mockup get param
  src/Model/DefaultMockup.php
Labels: Bug

#64 Improve exception for orders with aborted payment state
  src/Exception/ResponseWithAbortedPaymentStateException.php
  src/OrderManager/V7/OrderAgent.php
Labels: Improvement

#67 POEditor translations import
  src/Resources/translations/admin.cs.yaml
  src/Resources/translations/admin.de.yaml
  src/Resources/translations/admin.es.yaml
  src/Resources/translations/admin.fr.yaml
  src/Resources/translations/admin.hu.yaml
  src/Resources/translations/admin.it.yaml
  src/Resources/translations/admin.nl.yaml
  src/Resources/translations/admin.pl.yaml
  src/Resources/translations/admin.sk.yaml
  src/Resources/translations/admin.th.yaml
Labels: Task

#53 [Task] Pre Release Todo
  composer.json
Labels: Task
