Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2023-04, with the labels that each got.

#15 Add config for order agent
  src/Resources/config/order_agent.yaml
Labels: Task

#22 [Bug]: types
  src/Controller/AdminOrderController.php
Labels: Bug

#16 Task: Composer require symfony/form
  composer.json
Labels: Task

#23 [Bug]: Type error
  src/Controller/AdminOrderController.php
Labels: Bug

#24 fix type error.
  src/Controller/AdminOrderController.php
Labels: Bug

#17 [Task]: Ecom Framework JS and CSS updates
  .gitignore
  composer.json
  package.json
  src/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  src/PimcoreEcommerceFrameworkBundle.php
  src/Resources/public/assets/bootstrap.js
  src/Resources/public/assets/flatpickr.js
  src/Resources/public/assets/leaflet.js
  src/Resources/public/assets/voucher.js
  src/Resources/public/build/ecommerceFramework/243.js
  src/Resources/public/build/ecommerceFramework/243.js.LICENSE.txt
  src/Resources/public/build/ecommerceFramework/261.js
  src/Resources/public/build/ecommerceFramework/261.js.LICENSE.txt
  src/Resources/public/build/ecommerceFramework/527.js
  src/Resources/public/build/ecommerceFramework/897.css
  src/Resources/public/build/ecommerceFramework/897.js
  src/Resources/public/build/ecommerceFramework/897.js.LICENSE.txt
  src/Resources/public/build/ecommerceFramework/bootstrap.js
  src/Resources/public/build/ecommerceFramework/entrypoints.json
  src/Resources/public/build/ecommerceFramework/flatpickr.css
  src/Resources/public/build/ecommerceFramework/flatpickr.js
  src/Resources/public/build/ecommerceFramework/images/layers-2x.8f2c4d11.png
  src/Resources/public/build/ecommerceFramework/images/layers-2x.png
  src/Resources/public/build/ecommerceFramework/images/layers.416d9136.png
  src/Resources/public/build/ecommerceFramework/images/layers.png
  src/Resources/public/build/ecommerceFramework/images/marker-icon-2x.png
  src/Resources/public/build/ecommerceFramework/images/marker-icon.2b3e1faf.png
  src/Resources/public/build/ecommerceFramework/images/marker-icon.png
  src/Resources/public/build/ecommerceFramework/images/marker-shadow.png
  src/Resources/public/build/ecommerceFramework/leaflet.css
  src/Resources/public/build/ecommerceFramework/leaflet.js
  src/Resources/public/build/ecommerceFramework/manifest.json
  src/Resources/public/build/ecommerceFramework/runtime.js
  src/Resources/public/build/ecommerceFramework/voucher.js
  src/Resources/public/js/voucherservice/voucherSeriesTabScript.js
  src/Resources/public/vendor/bootstrap4/css/bootstrap.css
  src/Resources/public/vendor/bootstrap4/css/bootstrap.min.css
  src/Resources/public/vendor/bootstrap4/js/bootstrap-native-v4.min.js
  src/Resources/public/vendor/chart.doughnut.js
  src/Resources/public/vendor/chart.min.js
  src/Resources/public/vendor/flatpickr.min.css
  src/Resources/public/vendor/flatpickr.min.js
  src/Resources/views/admin_order/detail.html.twig
  src/Resources/views/admin_order/item_cancel.html.twig
  src/Resources/views/admin_order/item_complaint.html.twig
  src/Resources/views/admin_order/item_edit.html.twig
  src/Resources/views/admin_order/list.html.twig
  src/Resources/views/back-office.html.twig
  src/Resources/views/voucher/parts/modals/cleanup_reservations_modal.html.twig
  src/Resources/views/voucher/parts/modals/pattern/cleanup_modal.html.twig
  src/Resources/views/voucher/parts/modals/pattern/generate_modal.html.twig
  src/Resources/views/voucher/parts/modals/single/assign_settings_modal.html.twig
  src/Resources/views/voucher/parts/paginator.html.twig
  src/Resources/views/voucher/voucher_code_tab_pattern.html.twig
  src/Resources/views/voucher/voucher_code_tab_single.html.twig
  src/Resources/views/voucher/voucher_layout.html.twig
  webpack.config.js
Labels: Task, BC-BREAK

#25 [Feature]: migrate all logs to Monolog
  src/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  src/OrderManager/V7/OrderAgent.php
  src/Resources/config/pimcore/config.yaml
  src/VoucherService/Statistic.php
Labels: Task

#20 [Task]: Check usages of Pimcore\Db\Helper::insertOrUpdate and ON DUPLICATE KEY
  src/IndexService/Worker/Helper/MySql.php
Labels: Task

#27 Mark service OrderAgent as lazy
  src/Resources/config/order_agent.yaml
Labels: Task

#29 Do not treat OrderAgent as service
  src/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  src/OrderManager/Order/AgentFactory.php
  src/Resources/config/order_agent.yaml
  src/Resources/config/order_manager.yaml
Labels: Bug, Task

#39 [Task] Setup codeception
  .github/ci/files/config/bundles.php
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yaml
  .github/workflows/codeception.yml
  composer.json
  tests/_bootstrap.php
Labels: Task

#38 [Task] Add PHP CS Fixer
  .github/workflows/php-cs-fixer.yaml
  .gitignore
  .php_cs.dist
  .php_cs.dist.php
Labels: Task

#47 [Task]: Rename .php_cs.dist.php to .php-cs-fixer.dist.php
  .github/workflows/php-cs-fixer.yaml
  .php-cs-fixer.dist.php
  src/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  src/IndexService/Worker/Helper/MySql.php
  src/OrderManager/Order/AgentFactory.php
  src/VoucherService/Statistic.php
  tests/Ecommerce/PricingManager/Rule/AbstractRuleTest.php
  tests/Ecommerce/PricingManager/RuleTest.php
Labels: Task

#37 [Task] Setup phpstan
  .github/ISSUE_TEMPLATE/Bug-Report.yml
  .github/ISSUE_TEMPLATE/Feature-Request.yml
  .github/ISSUE_TEMPLATE/Improvement.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ci/files/var/classes/DataObject/Customer/Listing.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrder/Listing.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrderItem/Listing.php
  .github/ci/files/var/classes/DataObject/OnlineShopTaxClass/Listing.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherSeries/Listing.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherToken/Listing.php
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/static-analysis.yml
  composer.json
  phpstan-baseline.neon
  phpstan-bootstrap.php
  phpstan.neon
  src/CartManager/CartPriceModificator/Discount.php
  src/CheckoutManager/V7/CheckoutManager.php
  src/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  src/FilterService/FilterType/Findologic/NumberRangeSelection.php
  src/FilterService/ListHelper.php
  src/IndexService/Config/DefaultMysql.php
  src/IndexService/IndexUpdateService.php
  src/OrderManager/Order/Listing.php
  src/OrderManager/V7/OrderAgent.php
  src/PricingManager/Environment.php
  src/PricingManager/EnvironmentInterface.php
  src/Type/Decimal.php
  src/VoucherService/DefaultService.php
  src/VoucherService/Reservation.php
  src/VoucherService/TokenManager/AbstractTokenManager.php
  src/VoucherService/TokenManager/Pattern.php
  src/VoucherService/TokenManager/TokenManagerInterface.php
Labels: Task

#32 [Task]: Move translation from installer csv to yml
  src/Resources/install/admin-translations/init.csv
  src/Resources/translations/admin.en.yaml
  src/Tools/Installer.php
Labels: Task

#43 [#41] Add method hasParam to DefaultMockup
  src/Model/DefaultMockup.php
Labels: Improvement

#42 [#40] Enable params with uppercase first letter
  src/Model/DefaultMockup.php
Labels: Improvement

#49 [Security] Fix XSS in name parameter of Pricing Rules
  composer.json
  src/PricingManager/Rule.php
  src/Resources/public/js/pricing/config/panel.js
Labels: Security

#51 [Pimcore 11] Exclude AdminBundle
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yaml
  composer.json
  src/Controller/AdminOrderController.php
  src/Controller/ConfigController.php
  src/Controller/IndexController.php
  src/Controller/PricingController.php
  src/Controller/VoucherController.php
  src/PimcoreEcommerceFrameworkBundle.php
Labels: Task
