Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2024-04, with the labels that each got.

#173 Fix OrderAgent: Use Carbon instead of DateTime for setPaymentFinished…
  src/OrderManager/V7/OrderAgent.php
Labels: Bug

#176 Unify CLA check
  .github/workflows/cla.yml
Labels: Improvement

#175 Fix: Pricing Rule Brackets don't work
  src/PricingManager/Condition/Bracket.php
Labels: Pimcore:ToDo

#161 Array flip makes voucher strings to int
  src/OrderManager/V7/OrderManager.php
  src/VoucherService/TokenManager/Single.php
Labels: Bug, Pimcore:ToDo

#180 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo
