Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2024-10, with the labels that each got.

#200 Set amount to the subtotal when the discount amount exceeds the subtotal
  src/PricingManager/Action/CartDiscount.php
  src/Resources/public/js/pricing/config/item.js
  src/Resources/translations/admin.en.yaml
Labels: Improvement, Pimcore:ToDo

#205 fix: category id needs to be casted to string for trim function
  src/FilterService/FilterType/MultiSelectCategory.php
Labels: Bug

#206 fix: .map(Number) creates problems if preselect is not an id but a string
  src/Resources/public/js/indexfieldselectionfield/tags/indexFieldSelection.js
Labels: Bug, Pimcore:ToDo
