Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2024-03, with the labels that each got.

#171 fix quotation for defaultmysql
  src/IndexService/ProductList/DefaultMysql.php
  src/IndexService/ProductList/DefaultMysql/Dao.php
Labels: Bug

#163 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
Labels: sync

#167 [bugfix] Process two-dimensional arrays from DefaultBrickGetterSequen…
  src/IndexService/Getter/DefaultBrickGetterSequenceToMultiselect.php
Labels: Bug, Pimcore:ToDo
