Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2024-11, with the labels that each got.

#207 [Task][BC-Break] Unify OpenSearch and ElasticSearch
  doc/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/19_Upgrade_Notes/README.md
  src/Command/IndexService/EsSyncCommand.php
  src/Command/IndexService/IndexSyncCommand.php
  src/FilterService/FilterType/ElasticSearch/Input.php
  src/FilterService/FilterType/ElasticSearch/MultiSelect.php
  src/FilterService/FilterType/ElasticSearch/MultiSelectFromMultiSelect.php
  src/FilterService/FilterType/ElasticSearch/MultiSelectRelation.php
  src/FilterService/FilterType/ElasticSearch/NumberRange.php
  src/FilterService/FilterType/ElasticSearch/NumberRangeSelection.php
  src/FilterService/FilterType/ElasticSearch/Select.php
  src/FilterService/FilterType/ElasticSearch/SelectCategory.php
  src/FilterService/FilterType/ElasticSearch/SelectClassificationStoreAttributes.php
  src/FilterService/FilterType/ElasticSearch/SelectFromMultiSelect.php
  src/FilterService/FilterType/ElasticSearch/SelectRelation.php
  src/FilterService/FilterType/SearchIndex/MultiSelect.php
  src/IndexService/Config/ElasticSearch.php
  src/IndexService/Config/SearchConfigInterface.php
  src/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  src/IndexService/ProductList/OpenSearch/AbstractOpenSearch.php
  src/IndexService/ProductList/TenantConfigInterface.php
  src/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  src/IndexService/Worker/IndexRefreshInterface.php
  src/IndexService/Worker/OpenSearch/AbstractOpenSearch.php
Labels: New Feature, BC-BREAK, Pimcore:ToDo

#213 Update MultiSelectFromMultiSelect filter for ElasticSearch
  src/FilterService/FilterType/ElasticSearch/MultiSelectFromMultiSelect.php
Labels: Pimcore:ToDo

#216 Bugfix(PricingRules): Prevent Error when adding a new Pricing Rule with a name that exists
  src/PricingManager/Rule/Dao.php
Labels: Bug
