Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2025-04, with the labels that each got.

#247 [Improvement]: Extendable ProductList\DefaultMysql\Dao class
  src/IndexService/ProductList/DefaultMysql/Dao.php
Labels: Improvement

#251 [Bugfix]: Fix price info quantity property type
  src/PriceSystem/AbstractPriceInfo.php
Labels: Bug

#245 [Improvement]: Change filter definition's page limit from float to int
  .github/ci/files/var/classes/DataObject/FilterDefinition.php
  src/Model/AbstractFilterDefinition.php
  src/Resources/install/class_sources/class_FilterDefinition_export.json
Labels: Improvement

#252 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
Labels: Task

#233 Fix boolean types in ProductList::addCondition()
  doc/03_Installation/01_Upgrade_Notes.md
  src/IndexService/ProductList/DefaultFindologic.php
  src/IndexService/ProductList/DefaultMysql.php
  src/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  src/IndexService/ProductList/OpenSearch/AbstractOpenSearch.php
  src/IndexService/ProductList/ProductListInterface.php
Labels: BC-BREAK, Pimcore:ToDo

#253 Fix codeception
  .github/workflows/codeception.yml
Labels: Task
