Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2025-02, with the labels that each got.

#225 Update MultiSelectFromMultiSelect.php
  src/FilterService/FilterType/MultiSelectFromMultiSelect.php
Labels: Pimcore:ToDo

#227 [Task] Update AbstractOfferToolProduct to accept int only
  composer.json
  doc/03_Installation/01_Upgrade_Notes.md
  doc/19_Upgrade_Notes/README.md
  src/OfferTool/AbstractOfferToolProduct.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#228 [Bug]: Check if ecommerce mandatory class definition exists before importing
  src/Tools/PaymentProviderInstaller.php
Labels: Task, Pimcore:ToDo

#234 [Task] Add container extension
  src/PimcoreEcommerceFrameworkBundle.php
Labels: Task, Pimcore:ToDo
