Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2025-05, with the labels that each got.

#256 [Bug] Fixed saving of pricing rules
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  src/Controller/PricingController.php
Labels: Bug

#229 Support for adjusting batch-size in ProcessUpdateIndexQueueCommand
  src/Command/IndexService/ProcessUpdateIndexQueueCommand.php
Labels: Pimcore:ToDo, Pimcore:Priority

#230 Exclude filters in aggregations conditionally
  src/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  src/IndexService/ProductList/OpenSearch/AbstractOpenSearch.php
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority
