Repository pimcore/ecommerce-framework-bundle, pull requests merged in 2025-03, with the labels that each got.

#231 SelectCategory type error
  src/FilterService/FilterType/ElasticSearch/SelectCategory.php
  src/FilterService/FilterType/SearchIndex/SelectCategory.php
Labels: Bug

#235 [Improvement]: Support Dbal 4
  src/OrderManager/Order/Listing.php
Labels: Improvement, Pimcore:Priority

#237 [Improvement]: Follow up support DBAL v4
  src/CartManager/Cart.php
  src/CartManager/Cart/Dao.php
  src/IndexService/Worker/ProductCentricBatchProcessingWorker.php
  src/OrderManager/Order/Listing.php
  src/OrderManager/Order/Listing/Filter/Product.php
  src/PricingManager/Rule/Dao.php
Labels: Improvement, Pimcore:Priority

#236 Fix: switch index alias requires opensearch admin privileges
  src/IndexService/Worker/OpenSearch/AbstractOpenSearch.php
Labels: Improvement
